version: '3.8'

services:
  api:
    build:
      context: ./NpsApi
      dockerfile: Dockerfile
    container_name: nps-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nps-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: npsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  frontend:
    build:
      context: ./nps-frontend
      dockerfile: Dockerfile
    container_name: nps-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

volumes:
  pgdata:
