version: '3.8'

services:
  api:
    build:
      context: ./NpsApi
      dockerfile: Dockerfile
    container_name: nps-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=npsdb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nps-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: npsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
